baseURL = 'https://agonzalv.github.io/'
languageCode = 'en-us'
title = 'Alexandre Gonzalvez'
theme = 'beautifulhugo'
metaDataFormat = "yaml"
enableRobotsTXT = true
pygmentsStyle = "trac"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
enableEmoji = true
#enableGitInfo = true

[Params]
  homeTitle = " " # Set a different text for the header on the home page
  subtitle = "Full-time postdoctoral researcher at CNRS, EMSEC/Capsule. "
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  #favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  #commit = "https://github.com/agonzalv/agonzalv.github.io/tree/"
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  #selfHosted = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  copyright = "CC BY-SA 4.0"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Alexandre Gonzalvez"
  website = ""
  email = "alexandre.gonzalvez AT irisa.fr"
  #facebook = "username"
  github = "agonzalv"
  gitlab = "alx4t1"
  #bitbucket = "username"
  twitter = "PetitGatooo"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    identifier = "CV"
    name = "CV"
    url = "page/pdf/CV_Alexandre_GONZALVEZ_EN.pdf"
    weight = 1


[[menu.main]]
    identifier = "Publications"
    name = "Publications"
    url = "page/publi"
    weight = 2

[[menu.main]]
    identifier = "Activities"
    name = "Activities"
    url = "page/research"
    weight = 3

#[[menu.main]]
#  name = "Tags"
#  pre = '<i class="fas fa-tags fa-lg"></i>'
#  url = "page/tags"
#  weight = 3

